# Main Config File for ServerControl

##############################################################################
#                                 Commands                                   #
##############################################################################
restart:
  # time in seconds to restart the server
  time: 10